// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgzAYTGTUBaOUB7JIcLNImTai25hmvA78',
    appId: '1:162583006610:web:3f669876e0c500b3ac454b',
    messagingSenderId: '162583006610',
    projectId: 'the-electrification-index',
    authDomain: 'the-electrification-index.firebaseapp.com',
    storageBucket: 'the-electrification-index.firebasestorage.app',
    measurementId: 'G-PFTWJEDLTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmKlV1bZQLlGwBVbmSkTAJ9Zo06FF-v70',
    appId: '1:162583006610:android:5344c2e6bcbf20a4ac454b',
    messagingSenderId: '162583006610',
    projectId: 'the-electrification-index',
    storageBucket: 'the-electrification-index.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdsY_-hvjvj4fZKBoSIRyIrrmtTVlvYQs',
    appId: '1:162583006610:ios:5a9d85f4a7e93cc7ac454b',
    messagingSenderId: '162583006610',
    projectId: 'the-electrification-index',
    storageBucket: 'the-electrification-index.firebasestorage.app',
    iosBundleId: 'com.example.code',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdsY_-hvjvj4fZKBoSIRyIrrmtTVlvYQs',
    appId: '1:162583006610:ios:5a9d85f4a7e93cc7ac454b',
    messagingSenderId: '162583006610',
    projectId: 'the-electrification-index',
    storageBucket: 'the-electrification-index.firebasestorage.app',
    iosBundleId: 'com.example.code',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgzAYTGTUBaOUB7JIcLNImTai25hmvA78',
    appId: '1:162583006610:web:3f669876e0c500b3ac454b',
    messagingSenderId: '162583006610',
    projectId: 'the-electrification-index',
    authDomain: 'the-electrification-index.firebaseapp.com',
    storageBucket: 'the-electrification-index.firebasestorage.app',
    measurementId: 'G-PFTWJEDLTQ',
  );
}
